### PR TITLE
change ts imports

### PR DESCRIPTION
**Pull request by ZakTax**
these imports work better for both firebase and firebase admin for some reason

### CODE REVIEW

**Comment by mickeyreiss** [comment]
@ZakTax please review the fixture diff

**Comment by mickeyreiss** [comment]
@ZakTax It looks like the CI failure is legitimate.

**Comment by ZakTax** [comment]
@mickeyreiss what do you do to recreate fixtures?

**Comment by mickeyreiss** [comment]
@ZakTax Added some instructions in #15

**Pull request merged**
